# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: hosted-win2019

variables:
  system_accesstoken: $(System.AccessToken)
  storage_name: 'policyexemptions'
  storage_container_name: 'policy'
  storage_rsg: 'WEU-RSG-PRIV-DNS'
  storage_blob_name: 'policyExemptions.csv'
  resource_subscription: 'rack-multi-hub-nonprod'
  csv_path: '$(System.DefaultWorkingDirectory)\csv\PolicyExemption.csv'
  automation_account: 
  automation_account_rsg:
  automation_runbook_name:
  automation_runbook_path: '$(System.DefaultWorkingDirectory)\runbooks\policy-exemption.ps1'
  sqlserver_name:
  sqldb_name:
  sqltable_name:
  client_id:
  tenant_id:

steps:
- checkout: self
  clean: true
  submodules: true
  persistCredentials: true

- task: AzurePowerShell@5
  displayName: 'Upload CSV to Blob Storage'
  enabled: true
  inputs:
    azureSubscription: HUB
    ScriptType: FilePath
    ScriptPath: '$(System.DefaultWorkingDirectory)\scripts\uploadblob.ps1'
    ScriptArguments: '-csvPath $(csv_path) -storagersg $(storage_rsg) -storageName $(storage_name) -storageContainer $(storage_container_name) -blobName $(storage_blob_name) -subscriptionName $(resource_subscription)'
    azurePowerShellVersion: LatestVersion
  env:
    System_DefaultWorkingDirectory : $(System.DefaultWorkingDirectory)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $()

- task: AzurePowerShell@5
  displayName: 'Publish Runbook to Automation Account'
  enabled: false
  inputs:
    azureSubscription: HUB
    ScriptType: FilePath
    ScriptPath: '$(System.DefaultWorkingDirectory)\scripts\publish.ps1'
    ScriptArguments: '-runbookPath $(automation_runbook_path) -automationAccountRSG $(automation_account_rsg) -automationAccountName $(automation_account) -runbookName $(automation_runbook_name) -subscriptionName $(resource_subscription)'
    azurePowerShellVersion: LatestVersion
  env:
    System_DefaultWorkingDirectory : $(System.DefaultWorkingDirectory)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $()

- task: AzurePowerShell@5
  displayName: 'Apply Policy Exemptions'
  enabled: true
  inputs:
    azureSubscription: HUB
    ScriptType: FilePath
    ScriptPath: '$(System.DefaultWorkingDirectory)\scripts\startrunbook.ps1'
    ScriptArguments: '-automationAccountRSG $(automation_account_rsg) -automationAccountName $(automation_account) -runbookName $(automation_runbook_name) -runbookParameters @{"csvName"="$(storage_blob_name)";"sqlServer"="$(sqlserver_name)";"sqlDBName"="$(sqldb_name)";"sqlTableName"="$(sqltable_name)";"storagersg"="$(storage_rsg)";"storageName"="$(storage_name)";"storageContainer"="$(storage_container_name)";"storageSubscription"="$(resource_subscription)"} -subscriptionName $(resource_subscription)'
    azurePowerShellVersion: LatestVersion
  env:
    System_DefaultWorkingDirectory : $(System.DefaultWorkingDirectory)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $()

- task: AzurePowerShell@5
  displayName: 'Remove CSV Blob from Storage'
  enabled: true
  inputs:
    azureSubscription: HUB
    ScriptType: FilePath
    ScriptPath: '$(System.DefaultWorkingDirectory)\scripts\removeblob.ps1'
    ScriptArguments: '-blobName "policy-exemptions.csv"'
    azurePowerShellVersion: LatestVersion
  env:
    System_DefaultWorkingDirectory : $(System.DefaultWorkingDirectory)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $()

- task: AzurePowerShell@5
  displayName: 'Clear CSV from Local Repo'
  enabled: true
  inputs:
    azureSubscription: HUB
    ScriptType: InlineScript
    Inline: |
     #Clear CSV File
     (Get-Content $(csv_path) |  Select-Object -First 1) | Out-File $(csv_path) -Force
    azurePowerShellVersion: LatestVersion
  env:
   System_DefaultWorkingDirectory : $(System.DefaultWorkingDirectory)

- script: |
    ECHO "Setting GIT config.."
    git config --global user.name "$(Build.RequestFor)"
    git config --global user.email "$(Build.RequestForEmail)"

    ECHO "GIT Checkout"
    git checkout -b $(Build.SourceBranchName)
    git pull origin $(Build.SourceBranchName)

    ECHO "GIT ADD..."
    git add -A

    ECHO "Commiting the changes..."
    git commit -m "Latest Customizations updated"
    
    ECHO "CHECK GIT STATUS..."
    git status

    ECHO "Pushing the changes..."
    git push -u origin $(Build.SourceBranchName)

    ECHO "Customization Committed Successfully"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Git Push Updated CSV file'
  continueOnError: true
  enabled: true
  env:
      system_accesstoken: $(System.AccessToken)


- task: DeleteFiles@1
  displayName: 'Delete files from $(System.DefaultWorkingDirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*'
    RemoveSourceFolder: true
  condition: succeededOrFailed()      