# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: hosted-win2019

variables:
  system_accesstoken: $(System.AccessToken)

steps:
- checkout: self
  clean: true
  submodules: true
  persistCredentials: true

- task: AzurePowerShell@5
  displayName: 'Apply Policy Exemptions'
  inputs:
    azureSubscription: HUB
    ScriptType: FilePath
    ScriptPath: '$(System.DefaultWorkingDirectory)\scripts\policy-exemption.ps1'
    ScriptArguments: '-csvPath $(System.DefaultWorkingDirectory)\csv\PolicyExemption.csv'
    azurePowerShellVersion: LatestVersion
  env:
    System_DefaultWorkingDirectory : $(System.DefaultWorkingDirectory)

- script: |
    ECHO "Setting GIT config.."
    git config --global user.name "$(Build.RequestFor)"
    git config --global user.email "$(Build.RequestForEmail)"

    ECHO "GIT Checkout"
    git checkout -b $(Build.SourceBranchName)
    git pull origin $(Build.SourceBranchName)

    ECHO "GIT ADD..."
    git add -A

    ECHO "Commiting the changes..."
    git commit -m "Latest Customizations updated"
    
    ECHO "CHECK GIT STATUS..."
    git status

    ECHO "Pushing the changes..."
    git push -u origin $(Build.SourceBranchName)

    ECHO "Customization Committed Successfully"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Resetting CSV file'
  continueOnError: true
  env:
      system_accesstoken: $(System.AccessToken)


- task: DeleteFiles@1
  displayName: 'Delete files from $(System.DefaultWorkingDirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*'
    RemoveSourceFolder: true
  condition: succeededOrFailed()      